#!/usr/bin/env python3
"""Configure the HLSL offload test suite for standalone execution.

Generates lit.site.cfg.py files for running the offload test suite from an
installed distribution, outside any LLVM/CMake build tree. Reads the
canonical lit.site.cfg.py.in template installed alongside this script and
substitutes @VAR@ tokens with values appropriate for *this* (test) machine.

Prerequisites on the target machine:
  * Python 3.6+
  * pip install lit pyyaml
  * GPU drivers (D3D12, Vulkan, or Metal depending on suite)
  * For non-clang suites: a DXC executable on PATH or via --dxc-path

Typical install layout this script expects:
  <prefix>/bin/                          tool binaries (offloader, FileCheck, ...)
  <prefix>/share/hlsl-test-suite/        this script + lit.site.cfg.py.in + test/

Usage:
  ./configure-test-suite.py --suite clang-d3d12
  lit run/test/clang-d3d12 -v
"""

import argparse
import os
import pathlib
import platform
import re
import shutil
import sys

# Suite name -> (d3d12, vk, mtl, clang, warp, lavapipe, description).
SUITES = {
    "d3d12": (True,False,False,False,False,False,"DXC-compiled shaders on DirectX 12"),
    "vk": (False, True, False, False, False, False, "DXC-compiled shaders on Vulkan"),
    "mtl": (False, False, True, False, False, False, "DXC-compiled shaders on Metal"),
    "clang-d3d12": (
        True,
        False,
        False,
        True,
        False,
        False,
        "Clang-compiled shaders on DirectX 12",
    ),
    "clang-vk": (
        False,
        True,
        False,
        True,
        False,
        False,
        "Clang-compiled shaders on Vulkan",
    ),
    "clang-mtl": (
        False,
        False,
        True,
        True,
        False,
        False,
        "Clang-compiled shaders on Metal",
    ),
    "warp-d3d12": (
        True,
        False,
        False,
        False,
        True,
        False,
        "DXC-compiled shaders on WARP (Windows)",
    ),
    "clang-warp-d3d12": (
        True,
        False,
        False,
        True,
        True,
        False,
        "Clang-compiled shaders on WARP (Windows)",
    ),
    "vk-lavapipe": (
        False,
        True,
        False,
        False,
        False,
        True,
        "DXC-compiled shaders on Lavapipe (Vulkan software rasterizer)",
    ),
    "clang-vk-lavapipe": (
        False,
        True,
        False,
        True,
        False,
        True,
        "Clang-compiled shaders on Lavapipe (Vulkan software rasterizer)",
    ),
}

# Self-contained replacement for @LIT_SITE_CFG_IN_HEADER@. The in-tree
# header (provided by LLVM's configure_lit_site_cfg) wraps paths with a
# helper that rewrites build-tree absolutes; here every path we substitute
# is already absolute and correct for the test runner, so `path()` is just
# an identity function.
HEADER = """\
# Autogenerated by configure-test-suite.py
# Do not edit - regenerate with configure-test-suite.py.
import os
import platform
def path(p):
    return p
"""


def emit_site_cfg(template_text, substitutions):
    """Replace @VAR@ tokens in template_text. Unsubstituted @VAR@ tokens
    produce a hard error so we don't silently ship a half-configured file."""
    text = template_text.replace("@LIT_SITE_CFG_IN_HEADER@", HEADER)
    for key, value in substitutions.items():
        text = text.replace("@{}@".format(key), value)
    # Catch any leftover @TOKEN@ that we didn't account for.
    leftover = re.findall(r"@[A-Za-z_][A-Za-z0-9_]*@", text)
    if leftover:
        raise SystemExit(
            "configure-test-suite.py: unsubstituted tokens in template: "
            + ", ".join(sorted(set(leftover)))
        )
    return text


def main():
    script_dir = pathlib.Path(__file__).resolve().parent
    default_prefix = (
        script_dir.parent.parent
    )  # <prefix>/share/hlsl-test-suite -> <prefix>

    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--suite",
        action="append",
        dest="suites",
        metavar="NAME",
        help="Test suite to configure (repeatable).",
    )
    p.add_argument(
        "--list-suites", action="store_true", help="List available suites and exit."
    )
    p.add_argument(
        "--prefix",
        type=pathlib.Path,
        default=default_prefix,
        help="Install prefix containing bin/ (default: auto-detected from script location).",
    )
    p.add_argument(
        "--bin-dir",
        type=pathlib.Path,
        default=None,
        help="Override directory containing tool binaries (default: <prefix>/bin).",
    )
    p.add_argument(
        "--output-dir",
        type=pathlib.Path,
        default=None,
        help="Output directory for generated configs (default: <script-dir>/run).",
    )
    p.add_argument(
        "--dxc-path",
        type=pathlib.Path,
        default=None,
        help="Path to dxc executable (for non-clang suites; default: from PATH).",
    )
    p.add_argument(
        "--golden-images",
        type=pathlib.Path,
        default=None,
        help="Override golden-images directory (default: <script-dir>/golden-images if present).",
    )
    p.add_argument(
        "--enable-debug",
        dest="enable_debug",
        action="store_true",
        default=True,
        help="Enable runtime debug layers (default: on).",
    )
    p.add_argument(
        "--no-debug",
        dest="enable_debug",
        action="store_false",
        help="Disable runtime debug layers.",
    )
    p.add_argument(
        "--enable-validation",
        action="store_true",
        default=False,
        help="Enable runtime validation layers (default: off).",
    )
    p.add_argument(
        "--os-name",
        default=platform.system(),
        help="Override CMAKE_SYSTEM_NAME-equivalent OS name (default: auto-detect).",
    )
    p.add_argument(
        "--warp-arch",
        default="",
        help="WARP_ARCHITECTURE value (only for *-warp-d3d12 suites).",
    )

    args = p.parse_args()

    if args.list_suites:
        print("Available test suites:")
        for name in sorted(SUITES):
            print("  {:<18s}  {}".format(name, SUITES[name][6]))
        return 0

    if not args.suites:
        p.error("--suite is required (use --list-suites to see options)")

    unknown = [s for s in args.suites if s not in SUITES]
    if unknown:
        p.error(
            "unknown suite(s): {} (available: {})".format(
                ", ".join(unknown), ", ".join(sorted(SUITES))
            )
        )

    bin_dir = (args.bin_dir or (args.prefix / "bin")).resolve()
    if not bin_dir.is_dir():
        p.error("bin dir does not exist: {}".format(bin_dir))

    template_path = script_dir / "lit.site.cfg.py.in"
    if not template_path.is_file():
        p.error("missing template alongside script: {}".format(template_path))
    template_text = template_path.read_text(encoding="utf-8")

    output_base = (args.output_dir or (script_dir / "run")).resolve()
    test_src_root = (script_dir / "test").resolve()
    if not test_src_root.is_dir():
        p.error("missing installed test sources: {}".format(test_src_root))

    # Resolve DXC if any non-clang suite is being configured.
    needs_dxc = any(not SUITES[s][3] for s in args.suites)
    dxc_path = args.dxc_path
    if needs_dxc and dxc_path is None:
        found = shutil.which("dxc") or shutil.which("dxc.exe")
        if found:
            dxc_path = pathlib.Path(found).resolve()
    if needs_dxc and (dxc_path is None or not dxc_path.is_file()):
        print(
            "warning: DXC not found; non-clang suites will not be able to compile shaders. "
            "Pass --dxc-path to silence this warning.",
            file=sys.stderr,
        )
        dxc_path = None
    dxc_dir = str(dxc_path.parent) if dxc_path is not None else ""

    # Golden images: prefer explicit path, then installed copy. An empty
    # string indicates "not configured" (lit.cfg.py treats it as such);
    # avoid resolving an empty pathlib.Path which would yield the cwd.
    if args.golden_images is not None:
        golden_dir = str(args.golden_images.resolve())
    else:
        candidate = script_dir / "golden-images"
        golden_dir = str(candidate.resolve()) if candidate.is_dir() else ""

    for suite in args.suites:
        d3d12, vk, mtl, clang, warp, lavapipe, _ = SUITES[suite]
        suite_obj_root = output_base
        suite_dir = output_base / "test" / suite
        suite_dir.mkdir(parents=True, exist_ok=True)

        substitutions = {
            "OFFLOADTEST_BINARY_DIR": str(suite_obj_root),
            # The directory containing test/lit.cfg.py. In an in-tree build
            # this is the project source dir; in the standalone install
            # layout it's the install share dir.
            "OFFLOADTEST_TEST_ROOT": str(test_src_root.parent),
            "LLVM_TOOLS_DIR": str(bin_dir),
            "DXC_EXECUTABLE": str(dxc_path) if dxc_path is not None else "",
            "SUPPORTS_SPIRV": "True" if vk else "False",
            "FORCE_CLANG": "True" if clang else "False",
            "FORCE_WARP": "True" if warp else "False",
            "FORCE_LAVAPIPE": "True" if lavapipe else "False",
            "WARP_ARCHITECTURE": args.warp_arch,
            "DXC_DIR": dxc_dir,
            "GOLDENIMAGE_DIR": golden_dir,
            "suite": suite,
            "TEST_d3d12": "True" if d3d12 else "False",
            "TEST_vk": "True" if vk else "False",
            "TEST_mtl": "True" if mtl else "False",
            "CMAKE_SYSTEM_NAME": args.os_name,
            "OFFLOADTEST_ENABLE_DEBUG": "1" if args.enable_debug else "0",
            "OFFLOADTEST_ENABLE_VALIDATION": "1" if args.enable_validation else "0",
        }

        site_cfg = suite_dir / "lit.site.cfg.py"
        site_cfg.write_text(
            emit_site_cfg(template_text, substitutions), encoding="utf-8"
        )
        print("configured: {}".format(site_cfg))

    print("\nrun with:")
    if len(args.suites) == 1:
        print("  lit {}".format(output_base / "test" / args.suites[0]))
    else:
        print("  lit {}".format(output_base / "test"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
