name: Execution Testing

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  Exec-Tests-Windows-AMD:
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        SKU: [windows-amd]
        TestTarget: [check-hlsl-d3d12, check-hlsl-clang-d3d12]

    uses: ./.github/workflows/build-and-test-callable.yaml
    with:
      OS: windows
      SKU: ${{ matrix.SKU }}
      TestTarget: ${{ matrix.TestTarget }}
      BuildType: Debug
      OffloadTest-branch: ${{ github.event.pull_request.head.sha }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DOFFLOADTEST_USE_CLANG_TIDY=On
