name: Windows D3D12 Warp Preview Clang

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:

jobs:
  Windows-D3D12-Warp-Clang:
    uses: ./.github/workflows/build-and-test-callable.yaml
    with:
      OS: windows
      SKU: windows-amd
      TestTarget: check-hlsl-clang-warp-d3d12
      OffloadTest-branch: ${{ github.ref }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DOFFLOADTEST_USE_CLANG_TIDY=On -DWARP_VERSION=1.0.15-preview
