name: Windows D3D12 AMD Clang GBV

permissions:
  contents: read

on:
  schedule:
    - cron: '0 6 * * 2-6' # Run daily at 10pm PST, Mon-Fri (6am UTC, Tue-Sat)

jobs:
  Windows-D3D12-AMD-Clang-GBV:
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/build-and-test-callable.yaml
    with:
      OS: windows
      SKU: windows-amd
      TestTarget: check-hlsl-clang-d3d12
      OffloadTest-branch: ${{ github.ref }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DOFFLOADTEST_USE_CLANG_TIDY=On -DOFFLOADTEST_ENABLE_VALIDATION=ON
