name: Windows D3D12 AMD DXC

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # run every 2 hours

jobs:
  Windows-D3D12-AMD-DXC:
    uses: ./.github/workflows/build-and-test-callable.yaml
    with:
      OS: windows
      SKU: windows-amd
      BuildType: Debug
      TestTarget: check-hlsl-d3d12
      OffloadTest-branch: ${{ github.ref }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
